### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by carmonac** [dpecos/node-redsys#2]
Hi there,
I'm trying to implement your code to create a virtual payment with redsys in my website made with Angular and express but there is no documentation about implementation from frontend code. Can you provide any example or sample of code to use your library?

Thank you.

**Comment by dpecos** [comment]
Hi,

Sorry but this module is no longer maintained, though it should still be working. I can't provide a working example because I no longer have access to it :(

That being said, Redsys can not work without a backend endpoint, so it's not possible to use this module from a 100% frontend environment.

Kind regards,

Dani.
